//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminSurveyLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminSurveyLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminSurveyLinks", typeof(ResViewAdminSurveyLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zu Umfrage nach 4 Wochen.
        /// </summary>
        public static string LblLinkSecondSurvey {
            get {
                return ResourceManager.GetString("LblLinkSecondSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zu Startumfrage.
        /// </summary>
        public static string LblLinkStartSurvey {
            get {
                return ResourceManager.GetString("LblLinkStartSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Umfragelink.
        /// </summary>
        public static string MsgBox_IncorrectSurveyLink_Caption {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectSurveyLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ein Umfragelink angegeben wird, muss dieser mit &quot;http://&quot; oder &quot;https://&quot; beginnen!.
        /// </summary>
        public static string MsgBox_IncorrectSurveyLink_Text {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectSurveyLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Umfragelink ein (beginnend mit &quot;http://&quot; oder &quot;https://&quot;).
        /// </summary>
        public static string PlaceholderSurveyLink {
            get {
                return ResourceManager.GetString("PlaceholderSurveyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links zu den Umfragen.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfrage-Links konnten nicht gespeichert werden.
        /// </summary>
        public static string TextSaveNoSuccess {
            get {
                return ResourceManager.GetString("TextSaveNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfrage-Links erfolgreich gespeichert.
        /// </summary>
        public static string TextSaveSuccess {
            get {
                return ResourceManager.GetString("TextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfragen.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
