//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminDeviceDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminDeviceDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminDeviceDetails", typeof(ResViewAdminDeviceDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string CmdBack {
            get {
                return ResourceManager.GetString("CmdBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endgültig löschen.
        /// </summary>
        public static string CmdDeleteUserPermanently {
            get {
                return ResourceManager.GetString("CmdDeleteUserPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string Col_AppVersion {
            get {
                return ResourceManager.GetString("Col_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätename.
        /// </summary>
        public static string Col_DevName {
            get {
                return ResourceManager.GetString("Col_DevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zuletzt online.
        /// </summary>
        public static string Col_LastOnline {
            get {
                return ResourceManager.GetString("Col_LastOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string Col_Manufacturer {
            get {
                return ResourceManager.GetString("Col_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell.
        /// </summary>
        public static string Col_Model {
            get {
                return ResourceManager.GetString("Col_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betriebssystem.
        /// </summary>
        public static string Col_OS {
            get {
                return ResourceManager.GetString("Col_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy, HH:mm.
        /// </summary>
        public static string DateAndTimeFormatString {
            get {
                return ResourceManager.GetString("DateAndTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string Lbl_CreatedAt {
            get {
                return ResourceManager.GetString("Lbl_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräteinfo.
        /// </summary>
        public static string Lbl_DeviceInfo {
            get {
                return ResourceManager.GetString("Lbl_DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe aktiv.
        /// </summary>
        public static string Lbl_FirstAidActive {
            get {
                return ResourceManager.GetString("Lbl_FirstAidActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Lbl_Id {
            get {
                return ResourceManager.GetString("Lbl_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Zugriff.
        /// </summary>
        public static string Lbl_LastAccess {
            get {
                return ResourceManager.GetString("Lbl_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Lbl_no {
            get {
                return ResourceManager.GetString("Lbl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startumfrage erledigt.
        /// </summary>
        public static string Lbl_StartSurveyDone {
            get {
                return ResourceManager.GetString("Lbl_StartSurveyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Lbl_yes {
            get {
                return ResourceManager.GetString("Lbl_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätedetails.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätedetails.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
