//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminFirstAidOverview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminFirstAidOverview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminFirstAidOverview", typeof(ResViewAdminFirstAidOverview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Col_Active {
            get {
                return ResourceManager.GetString("Col_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe Text.
        /// </summary>
        public static string Col_FirstAidText {
            get {
                return ResourceManager.GetString("Col_FirstAidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string Col_Number {
            get {
                return ResourceManager.GetString("Col_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Col_Title {
            get {
                return ResourceManager.GetString("Col_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Lbl_no {
            get {
                return ResourceManager.GetString("Lbl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisher wurden noch keine Erste Hilfe-Themen erfasst. Klicken Sie auf das Plus um neue hinzuzufügen..
        /// </summary>
        public static string Lbl_NoRecords {
            get {
                return ResourceManager.GetString("Lbl_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Lbl_yes {
            get {
                return ResourceManager.GetString("Lbl_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen?.
        /// </summary>
        public static string MsgBox_ReallyDelete_Caption {
            get {
                return ResourceManager.GetString("MsgBox_ReallyDelete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie dieses Erste Hilfe Thema wirklich löschen?.
        /// </summary>
        public static string MsgBox_ReallyDelete_Text {
            get {
                return ResourceManager.GetString("MsgBox_ReallyDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler.
        /// </summary>
        public static string MsgBox_SaveError_Caption {
            get {
                return ResourceManager.GetString("MsgBox_SaveError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderung konnte nicht gespeichert werden..
        /// </summary>
        public static string MsgBox_SaveError_Text {
            get {
                return ResourceManager.GetString("MsgBox_SaveError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe Übersicht.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
