//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminEditInfoText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminEditInfoText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminEditInfoText", typeof(ResViewAdminEditInfoText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Cmd_Back {
            get {
                return ResourceManager.GetString("Cmd_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Lbl_Active {
            get {
                return ResourceManager.GetString("Lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Bild.
        /// </summary>
        public static string Lbl_InfoPic {
            get {
                return ResourceManager.GetString("Lbl_InfoPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Text.
        /// </summary>
        public static string Lbl_InfoText {
            get {
                return ResourceManager.GetString("Lbl_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        public static string Lbl_Number {
            get {
                return ResourceManager.GetString("Lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeige in App nur.
        /// </summary>
        public static string Lbl_ShowOnlyOnFirstAid_Part1 {
            get {
                return ResourceManager.GetString("Lbl_ShowOnlyOnFirstAid_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wenn Erste Hilfe aktiviert.
        /// </summary>
        public static string Lbl_ShowOnlyOnFirstAid_Part2 {
            get {
                return ResourceManager.GetString("Lbl_ShowOnlyOnFirstAid_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Lbl_Title {
            get {
                return ResourceManager.GetString("Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weblink.
        /// </summary>
        public static string Lbl_Weblink {
            get {
                return ResourceManager.GetString("Lbl_Weblink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Upload des Bildes.
        /// </summary>
        public static string MsgBox_ImageSaveError_Caption {
            get {
                return ResourceManager.GetString("MsgBox_ImageSaveError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild konnte nicht gespeichert werden.
        /// </summary>
        public static string MsgBox_ImageSaveError_Text {
            get {
                return ResourceManager.GetString("MsgBox_ImageSaveError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Weblink.
        /// </summary>
        public static string MsgBox_IncorrectWeblink_Caption {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectWeblink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ein Weblink angegeben wird, muss dieser mit &quot;http://&quot; oder &quot;https://&quot; beginnen!.
        /// </summary>
        public static string MsgBox_IncorrectWeblink_Text {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectWeblink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Infotext ein.
        /// </summary>
        public static string PlaceHolderText {
            get {
                return ResourceManager.GetString("PlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Titel ein.
        /// </summary>
        public static string PlaceHolderTitle {
            get {
                return ResourceManager.GetString("PlaceHolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Weblink ein (beginnend mit &quot;http://&quot; oder &quot;https://&quot;).
        /// </summary>
        public static string PlaceholderWebLink {
            get {
                return ResourceManager.GetString("PlaceholderWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotext bearbeiten.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotext.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
