//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminAccountSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminAccountSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminAccountSettings", typeof(ResViewAdminAccountSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string CmdLogout {
            get {
                return ResourceManager.GetString("CmdLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string Lbl_NewPassword {
            get {
                return ResourceManager.GetString("Lbl_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        public static string Lbl_RepeatNewPassword {
            get {
                return ResourceManager.GetString("Lbl_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Lbl_Username {
            get {
                return ResourceManager.GetString("Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten erfolgreich geändert!.
        /// </summary>
        public static string MsgBoxText_settings_updated_success {
            get {
                return ResourceManager.GetString("MsgBoxText_settings_updated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Passwort.
        /// </summary>
        public static string MsgBoxText_wrongPW {
            get {
                return ResourceManager.GetString("MsgBoxText_wrongPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoeinstellungen.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoeinstellungen.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
