//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources.ResAdminApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAdminEditFirstAid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAdminEditFirstAid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResAdminApps.ResViewAdminEditFirstAid", typeof(ResViewAdminEditFirstAid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Cmd_Back {
            get {
                return ResourceManager.GetString("Cmd_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Lbl_Active {
            get {
                return ResourceManager.GetString("Lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe Text.
        /// </summary>
        public static string Lbl_FirstAidText {
            get {
                return ResourceManager.GetString("Lbl_FirstAidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis bei.
        /// </summary>
        public static string Lbl_HintForMissingAnswers_Part1 {
            get {
                return ResourceManager.GetString("Lbl_HintForMissingAnswers_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehlenden Fragen.
        /// </summary>
        public static string Lbl_HintForMissingAnswers_Part2 {
            get {
                return ResourceManager.GetString("Lbl_HintForMissingAnswers_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Lbl_Link {
            get {
                return ResourceManager.GetString("Lbl_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisher keine Bewertungen abgegeben.
        /// </summary>
        public static string Lbl_NoRatingsGiven {
            get {
                return ResourceManager.GetString("Lbl_NoRatingsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        public static string Lbl_Number {
            get {
                return ResourceManager.GetString("Lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string Lbl_Pic {
            get {
                return ResourceManager.GetString("Lbl_Pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragen.
        /// </summary>
        public static string Lbl_Questions {
            get {
                return ResourceManager.GetString("Lbl_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung.
        /// </summary>
        public static string Lbl_RatingAvg {
            get {
                return ResourceManager.GetString("Lbl_RatingAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertungstext.
        /// </summary>
        public static string Lbl_RatingText {
            get {
                return ResourceManager.GetString("Lbl_RatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Lbl_Text {
            get {
                return ResourceManager.GetString("Lbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Lbl_Title {
            get {
                return ResourceManager.GetString("Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weblink.
        /// </summary>
        public static string Lbl_Weblink {
            get {
                return ResourceManager.GetString("Lbl_Weblink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Hinweislink.
        /// </summary>
        public static string MsgBox_IncorrectHintLink_Caption {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectHintLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ein Link für den Hinweis angegeben wird, muss dieser mit &quot;http://&quot; oder &quot;https://&quot; beginnen!.
        /// </summary>
        public static string MsgBox_IncorrectHintLink_Text {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectHintLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Weblink.
        /// </summary>
        public static string MsgBox_IncorrectWeblink_Caption {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectWeblink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ein Weblink angegeben wird, muss dieser mit &quot;http://&quot; oder &quot;https://&quot; beginnen!.
        /// </summary>
        public static string MsgBox_IncorrectWeblink_Text {
            get {
                return ResourceManager.GetString("MsgBox_IncorrectWeblink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Link für den Hinweis ein (beginnend mit &quot;http://&quot; oder &quot;https://&quot;).
        /// </summary>
        public static string PlaceholderHintLink {
            get {
                return ResourceManager.GetString("PlaceholderHintLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Hinweis ein.
        /// </summary>
        public static string PlaceholderHintText {
            get {
                return ResourceManager.GetString("PlaceholderHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Bewertungstext ein.
        /// </summary>
        public static string PlaceholderRating {
            get {
                return ResourceManager.GetString("PlaceholderRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Erste Hilfe Text ein.
        /// </summary>
        public static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Titel ein.
        /// </summary>
        public static string PlaceholderTitle {
            get {
                return ResourceManager.GetString("PlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einen Weblink ein (beginnend mit &quot;http://&quot; oder &quot;https://&quot;).
        /// </summary>
        public static string PlaceholderWebLink {
            get {
                return ResourceManager.GetString("PlaceholderWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe bearbeiten.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Hilfe.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
