//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPushTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPushTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServer.Resources.ResPushTexts", typeof(ResPushTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Fokuszeit endet.
        /// </summary>
        public static string Msg_Fokus_End {
            get {
                return ResourceManager.GetString("Msg_Fokus_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Fokuszeit beginnt.
        /// </summary>
        public static string Msg_Fokus_Start {
            get {
                return ResourceManager.GetString("Msg_Fokus_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Pause endet.
        /// </summary>
        public static string Msg_Pause_End {
            get {
                return ResourceManager.GetString("Msg_Pause_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sollten eine Pause machen.
        /// </summary>
        public static string Msg_Pause_Start {
            get {
                return ResourceManager.GetString("Msg_Pause_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Arbeit endet.
        /// </summary>
        public static string Msg_Work_End {
            get {
                return ResourceManager.GetString("Msg_Work_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Arbeit beginnt.
        /// </summary>
        public static string Msg_Work_Start {
            get {
                return ResourceManager.GetString("Msg_Work_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokus.
        /// </summary>
        public static string Title_Fokus {
            get {
                return ResourceManager.GetString("Title_Fokus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Title_Pause {
            get {
                return ResourceManager.GetString("Title_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit.
        /// </summary>
        public static string Title_Work {
            get {
                return ResourceManager.GetString("Title_Work", resourceCulture);
            }
        }
    }
}
