//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewDatabaseUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewDatabaseUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServer.Resources.ResViewDatabaseUser", typeof(ResViewDatabaseUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dc Nachricht an alle Benutzer.
        /// </summary>
        public static string Btn_SendDcToAll {
            get {
                return ResourceManager.GetString("Btn_SendDcToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dc senden.
        /// </summary>
        public static string Btn_SendDcToCertain {
            get {
                return ResourceManager.GetString("Btn_SendDcToCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Nachricht an alle Benutzer.
        /// </summary>
        public static string Btn_SendPushToAll {
            get {
                return ResourceManager.GetString("Btn_SendPushToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Nachricht an alle Benutzer.
        /// </summary>
        public static string Btn_SendSmsToAll {
            get {
                return ResourceManager.GetString("Btn_SendSmsToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugeordnete Geräte.
        /// </summary>
        public static string Col_Assigned_Devices {
            get {
                return ResourceManager.GetString("Col_Assigned_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        public static string Col_CreatedOn {
            get {
                return ResourceManager.GetString("Col_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardsprache.
        /// </summary>
        public static string Col_Default_Language {
            get {
                return ResourceManager.GetString("Col_Default_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse.
        /// </summary>
        public static string Col_Email {
            get {
                return ResourceManager.GetString("Col_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email bestätigt?.
        /// </summary>
        public static string Col_Email_Verified {
            get {
                return ResourceManager.GetString("Col_Email_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Col_FirstName {
            get {
                return ResourceManager.GetString("Col_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ID.
        /// </summary>
        public static string Col_Id {
            get {
                return ResourceManager.GetString("Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Col_LastName {
            get {
                return ResourceManager.GetString("Col_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesperrt?.
        /// </summary>
        public static string Col_Locked {
            get {
                return ResourceManager.GetString("Col_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        public static string Col_PhoneNumber {
            get {
                return ResourceManager.GetString("Col_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer bestätigt.
        /// </summary>
        public static string Col_PhoneNumber_Verified {
            get {
                return ResourceManager.GetString("Col_PhoneNumber_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGB bestätigt.
        /// </summary>
        public static string Col_Tac_Confirmed {
            get {
                return ResourceManager.GetString("Col_Tac_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigte AGB Version.
        /// </summary>
        public static string Col_Tac_Version {
            get {
                return ResourceManager.GetString("Col_Tac_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Col_UserName {
            get {
                return ResourceManager.GetString("Col_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Command_Cancel {
            get {
                return ResourceManager.GetString("Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperren.
        /// </summary>
        public static string Command_Lock {
            get {
                return ResourceManager.GetString("Command_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push senden.
        /// </summary>
        public static string Command_SendPush {
            get {
                return ResourceManager.GetString("Command_SendPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS senden.
        /// </summary>
        public static string Command_SendSms {
            get {
                return ResourceManager.GetString("Command_SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entsperren.
        /// </summary>
        public static string Command_UnLock {
            get {
                return ResourceManager.GetString("Command_UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dc Text.
        /// </summary>
        public static string Label_DcText {
            get {
                return ResourceManager.GetString("Label_DcText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Text.
        /// </summary>
        public static string Label_SmsText {
            get {
                return ResourceManager.GetString("Label_SmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die Nachricht ein.
        /// </summary>
        public static string MessagePlaceHolder {
            get {
                return ResourceManager.GetString("MessagePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Informationen über die Datenbankbenutzer.
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welche Benutzer sind in der Datenbank hinterlegt?.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle.
        /// </summary>
        public static string Word_all {
            get {
                return ResourceManager.GetString("Word_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        public static string Word_to {
            get {
                return ResourceManager.GetString("Word_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string Word_User {
            get {
                return ResourceManager.GetString("Word_User", resourceCulture);
            }
        }
    }
}
