//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewDatabaseDeviceStatistics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewDatabaseDeviceStatistics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServer.Resources.ResViewDatabaseDeviceStatistics", typeof(ResViewDatabaseDeviceStatistics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung der Android Betriebssystemversionen.
        /// </summary>
        public static string Chart_Android_Os_Versions {
            get {
                return ResourceManager.GetString("Chart_Android_Os_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung der unterschiedlichen Appversionen.
        /// </summary>
        public static string Chart_App_Versions {
            get {
                return ResourceManager.GetString("Chart_App_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung der IOS Betriebssystemversionen.
        /// </summary>
        public static string Chart_Ios_Os_Versions {
            get {
                return ResourceManager.GetString("Chart_Ios_Os_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung der Aktualität der App Versionen.
        /// </summary>
        public static string Chart_Os_Actuality {
            get {
                return ResourceManager.GetString("Chart_Os_Actuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung der Betriebssysteme.
        /// </summary>
        public static string Chart_Os_Percentages {
            get {
                return ResourceManager.GetString("Chart_Os_Percentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Datenbankgerätestatistik.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Version.
        /// </summary>
        public static string OS_Actuality_New_Version {
            get {
                return ResourceManager.GetString("OS_Actuality_New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veraltete Version.
        /// </summary>
        public static string Os_Actuality_Old_Version {
            get {
                return ResourceManager.GetString("Os_Actuality_Old_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Version.
        /// </summary>
        public static string Os_Actuality_Version_Not_Found {
            get {
                return ResourceManager.GetString("Os_Actuality_Version_Not_Found", resourceCulture);
            }
        }
    }
}
