//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewDatabaseDevices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewDatabaseDevices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServer.Resources.ResViewDatabaseDevices", typeof(ResViewDatabaseDevices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie die Version der App ändern, werden alle Geräte, die diese Version noch nicht installiert haben, benachrichtigt..
        /// </summary>
        public static string AppVersion_Description {
            get {
                return ResourceManager.GetString("AppVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dc Nachricht an alle Geräte.
        /// </summary>
        public static string Btn_SendDcToAll {
            get {
                return ResourceManager.GetString("Btn_SendDcToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dc senden.
        /// </summary>
        public static string Btn_SendDcToCertain {
            get {
                return ResourceManager.GetString("Btn_SendDcToCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Nachricht an alle Geräte.
        /// </summary>
        public static string Btn_SendPushToAll {
            get {
                return ResourceManager.GetString("Btn_SendPushToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push senden.
        /// </summary>
        public static string Btn_SendPushToCertain {
            get {
                return ResourceManager.GetString("Btn_SendPushToCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string Col_App_Version {
            get {
                return ResourceManager.GetString("Col_App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardwareId.
        /// </summary>
        public static string Col_Device_HardwareId {
            get {
                return ResourceManager.GetString("Col_Device_HardwareId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätenummer.
        /// </summary>
        public static string Col_Device_Id {
            get {
                return ResourceManager.GetString("Col_Device_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string Col_Device_Manufacturer {
            get {
                return ResourceManager.GetString("Col_Device_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modellname.
        /// </summary>
        public static string Col_Device_Model {
            get {
                return ResourceManager.GetString("Col_Device_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätename.
        /// </summary>
        public static string Col_Device_Name {
            get {
                return ResourceManager.GetString("Col_Device_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PushToken.
        /// </summary>
        public static string Col_Device_PushToken {
            get {
                return ResourceManager.GetString("Col_Device_PushToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätetyp.
        /// </summary>
        public static string Col_Device_Type {
            get {
                return ResourceManager.GetString("Col_Device_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läuft die App?.
        /// </summary>
        public static string Col_Is_App_Running {
            get {
                return ResourceManager.GetString("Col_Is_App_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt online.
        /// </summary>
        public static string Col_Last_Time_Online {
            get {
                return ResourceManager.GetString("Col_Last_Time_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betriebssystem Version.
        /// </summary>
        public static string Col_Os_Version {
            get {
                return ResourceManager.GetString("Col_Os_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattform.
        /// </summary>
        public static string Col_Platform {
            get {
                return ResourceManager.GetString("Col_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string Col_User {
            get {
                return ResourceManager.GetString("Col_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ID.
        /// </summary>
        public static string Col_User_Id {
            get {
                return ResourceManager.GetString("Col_User_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welche Geräte sind gerade angemeldet in der Datenbank?.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Datenbankgeräte.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text der Benachrichtigung.
        /// </summary>
        public static string lable_messagetext {
            get {
                return ResourceManager.GetString("lable_messagetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel der Benachrichtigung.
        /// </summary>
        public static string lable_messagetitel {
            get {
                return ResourceManager.GetString("lable_messagetitel", resourceCulture);
            }
        }
    }
}
