//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewSettings", typeof(ResViewSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft To-Do.
        /// </summary>
        public static string Cmd_MsToDo {
            get {
                return ResourceManager.GetString("Cmd_MsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planarbeitszeiten.
        /// </summary>
        public static string Cmd_PlannedWorkingTime {
            get {
                return ResourceManager.GetString("Cmd_PlannedWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Nachrichten.
        /// </summary>
        public static string Cmd_PushMessages {
            get {
                return ResourceManager.GetString("Cmd_PushMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genauigkeit.
        /// </summary>
        public static string Lbl_Accuracy {
            get {
                return ResourceManager.GetString("Lbl_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisches Arbeitsende.
        /// </summary>
        public static string Lbl_AutoWorkEnd {
            get {
                return ResourceManager.GetString("Lbl_AutoWorkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatischer Arbeitsbeginn.
        /// </summary>
        public static string Lbl_AutoWorkStart {
            get {
                return ResourceManager.GetString("Lbl_AutoWorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler. Probiere es bitte erneut! .
        /// </summary>
        public static string MsgBox_CaptionSaveError {
            get {
                return ResourceManager.GetString("MsgBox_CaptionSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern erfolgreich.
        /// </summary>
        public static string MsgBox_CaptionSaveSuccess {
            get {
                return ResourceManager.GetString("MsgBox_CaptionSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen konnten nicht gespeichert werden. Probiere es bitte erneut! .
        /// </summary>
        public static string MsgBox_TextSaveError {
            get {
                return ResourceManager.GetString("MsgBox_TextSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen wurden gespeichert..
        /// </summary>
        public static string MsgBox_TextSaveSuccess {
            get {
                return ResourceManager.GetString("MsgBox_TextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutengenau.
        /// </summary>
        public static string PickerItem_1 {
            get {
                return ResourceManager.GetString("PickerItem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 min.
        /// </summary>
        public static string PickerItem_2 {
            get {
                return ResourceManager.GetString("PickerItem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 min.
        /// </summary>
        public static string PickerItem_3 {
            get {
                return ResourceManager.GetString("PickerItem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 min.
        /// </summary>
        public static string PickerItem_4 {
            get {
                return ResourceManager.GetString("PickerItem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min.
        /// </summary>
        public static string PickerItem_5 {
            get {
                return ResourceManager.GetString("PickerItem_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
