//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewLogin", typeof(ResViewLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Microsoft Login.
        /// </summary>
        public static string CheckingMsLogin {
            get {
                return ResourceManager.GetString("CheckingMsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login erfolgreich; Fehler beim Anmelden des Users.
        /// </summary>
        public static string ErrorLoginUser {
            get {
                return ResourceManager.GetString("ErrorLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login erfolgreich; Fehler beim Anlegen des Users.
        /// </summary>
        public static string ErrorRegisterUser {
            get {
                return ResourceManager.GetString("ErrorRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für die Nutzung dieser App benötigst du ein Microsoft-Konto. Wenn du keines hast, lege eine Outlook-Email-Adresse an. Damit kannst du dich anmelden..
        /// </summary>
        public static string LoginInfoText {
            get {
                return ResourceManager.GetString("LoginInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Serververbindung, bitte überprüfe deine Internetverbindung!.
        /// </summary>
        public static string LoginNotCompletedTryAgain {
            get {
                return ResourceManager.GetString("LoginNotCompletedTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login abgeschlossen, starte Login..
        /// </summary>
        public static string MsLoginCompletedStartingLogin {
            get {
                return ResourceManager.GetString("MsLoginCompletedStartingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login nicht bereit.
        /// </summary>
        public static string MsLoginNotReady {
            get {
                return ResourceManager.GetString("MsLoginNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login abgeschlossen, unbekannter User, leite Registrierung ein.
        /// </summary>
        public static string MsLoginUnknownUser {
            get {
                return ResourceManager.GetString("MsLoginUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Serververbindung, bitte überprüfe deine Internetverbindung!.
        /// </summary>
        public static string NoServerConnection {
            get {
                return ResourceManager.GetString("NoServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Serververbindung, bitte überprüfe deine Internetverbindung!.
        /// </summary>
        public static string SignInOkUserError {
            get {
                return ResourceManager.GetString("SignInOkUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du wirst zu deinem Microsoft Login weitergeleitet! .
        /// </summary>
        public static string StartingMsLogin {
            get {
                return ResourceManager.GetString("StartingMsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte um Testfeedback an biss@fotec.at. Bitte geben Sie auch die E-Mail Adresse mit der Sie sich angemeldet haben an..
        /// </summary>
        public static string TestFeedback {
            get {
                return ResourceManager.GetString("TestFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldefehler.
        /// </summary>
        public static string TestFeedbackCaption {
            get {
                return ResourceManager.GetString("TestFeedbackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du wirst angemeldet. Bitte kurz um Geduld! .
        /// </summary>
        public static string TryToLogin {
            get {
                return ResourceManager.GetString("TryToLogin", resourceCulture);
            }
        }
    }
}
