//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewSettingsPush {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewSettingsPush() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewSettingsPush", typeof(ResViewSettingsPush).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Einstellungen öffnen.
        /// </summary>
        public static string Cmd_PushSettings {
            get {
                return ResourceManager.GetString("Cmd_PushSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Nachrichten aktiviert:.
        /// </summary>
        public static string Lbl_Active {
            get {
                return ResourceManager.GetString("Lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokus/Projekt Ende.
        /// </summary>
        public static string Lbl_FocusEnd {
            get {
                return ResourceManager.GetString("Lbl_FocusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freizeit.
        /// </summary>
        public static string Lbl_Freetime {
            get {
                return ResourceManager.GetString("Lbl_Freetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Ende.
        /// </summary>
        public static string Lbl_PauseEnd {
            get {
                return ResourceManager.GetString("Lbl_PauseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Push Nachrichten sind deaktiviert. Aktiviere die Push-Nachrichten um weitere Optionen anzuzeigen..
        /// </summary>
        public static string Lbl_PushDisabled {
            get {
                return ResourceManager.GetString("Lbl_PushDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerung Pause.
        /// </summary>
        public static string Lbl_ReminderPause {
            get {
                return ResourceManager.GetString("Lbl_ReminderPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Lbl_Timer {
            get {
                return ResourceManager.GetString("Lbl_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsende.
        /// </summary>
        public static string Lbl_WorkEnd {
            get {
                return ResourceManager.GetString("Lbl_WorkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit in Freizeit?.
        /// </summary>
        public static string Lbl_WorkInFreetime {
            get {
                return ResourceManager.GetString("Lbl_WorkInFreetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsbeginn.
        /// </summary>
        public static string Lbl_WorkStart {
            get {
                return ResourceManager.GetString("Lbl_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht unterstützt auf der aktuellen Plattform!.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen Push-Nachrichten.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Nachrichten.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
