//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewMenu", typeof(ResViewMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrundaktivitäten.
        /// </summary>
        public static string CmdBackground {
            get {
                return ResourceManager.GetString("CmdBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der im Hintergrund laufenden Tätigkeiten.
        /// </summary>
        public static string CmdBackgroundToolTip {
            get {
                return ResourceManager.GetString("CmdBackgroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string CmdChat {
            get {
                return ResourceManager.GetString("CmdChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat demo.
        /// </summary>
        public static string CmdChatToolTip {
            get {
                return ResourceManager.GetString("CmdChatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwicklerinformationen.
        /// </summary>
        public static string CmdDeveloperInfo {
            get {
                return ResourceManager.GetString("CmdDeveloperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen für Entwickler.
        /// </summary>
        public static string CmdDeveloperInfoToolTip {
            get {
                return ResourceManager.GetString("CmdDeveloperInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayausrichtung.
        /// </summary>
        public static string CmdDisplayOrientation {
            get {
                return ResourceManager.GetString("CmdDisplayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayausrichtung sperren.
        /// </summary>
        public static string CmdDisplayOrientationToolTip {
            get {
                return ResourceManager.GetString("CmdDisplayOrientationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht stören.
        /// </summary>
        public static string CmdDontDisturb {
            get {
                return ResourceManager.GetString("CmdDontDisturb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen für &quot;Nicht stören&quot; öffnen.
        /// </summary>
        public static string CmdDontDisturbToolTip {
            get {
                return ResourceManager.GetString("CmdDontDisturbToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string CmdFeedback {
            get {
                return ResourceManager.GetString("CmdFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string CmdFeedbackToolTip {
            get {
                return ResourceManager.GetString("CmdFeedbackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien.
        /// </summary>
        public static string CmdFileAccess {
            get {
                return ResourceManager.GetString("CmdFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateisystem.
        /// </summary>
        public static string CmdFileAccessToolTip {
            get {
                return ResourceManager.GetString("CmdFileAccessToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me-Time.
        /// </summary>
        public static string CmdFirstAid {
            get {
                return ResourceManager.GetString("CmdFirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me-Time öffnen.
        /// </summary>
        public static string CmdFirstAidToolTip {
            get {
                return ResourceManager.GetString("CmdFirstAidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf.
        /// </summary>
        public static string CmdHistory {
            get {
                return ResourceManager.GetString("CmdHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf.
        /// </summary>
        public static string CmdHistoryToolTip {
            get {
                return ResourceManager.GetString("CmdHistoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Tag.
        /// </summary>
        public static string CmdHome {
            get {
                return ResourceManager.GetString("CmdHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Tag.
        /// </summary>
        public static string CmdHomeToolTip {
            get {
                return ResourceManager.GetString("CmdHomeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        public static string CmdImages {
            get {
                return ResourceManager.GetString("CmdImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info und Kontakt.
        /// </summary>
        public static string CmdInfo {
            get {
                return ResourceManager.GetString("CmdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info und Kontakt.
        /// </summary>
        public static string CmdInfoToolTip {
            get {
                return ResourceManager.GetString("CmdInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string CmdLogout {
            get {
                return ResourceManager.GetString("CmdLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string CmdLogoutToolTip {
            get {
                return ResourceManager.GetString("CmdLogoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte.
        /// </summary>
        public static string CmdMap {
            get {
                return ResourceManager.GetString("CmdMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte.
        /// </summary>
        public static string CmdMapToolTip {
            get {
                return ResourceManager.GetString("CmdMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Profil.
        /// </summary>
        public static string CmdMe {
            get {
                return ResourceManager.GetString("CmdMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Account.
        /// </summary>
        public static string CmdMeToolTip {
            get {
                return ResourceManager.GetString("CmdMeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string CmdPushNotifications {
            get {
                return ResourceManager.GetString("CmdPushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Benachrichtigungen senden.
        /// </summary>
        public static string CmdPushNotificationsToolTip {
            get {
                return ResourceManager.GetString("CmdPushNotificationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string CmdRadList {
            get {
                return ResourceManager.GetString("CmdRadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Demo.
        /// </summary>
        public static string CmdRadListToolTip {
            get {
                return ResourceManager.GetString("CmdRadListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string CmdScanner {
            get {
                return ResourceManager.GetString("CmdScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string CmdSettings {
            get {
                return ResourceManager.GetString("CmdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen öffnen.
        /// </summary>
        public static string CmdSettingsToolTip {
            get {
                return ResourceManager.GetString("CmdSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalR.
        /// </summary>
        public static string CmdSignalR {
            get {
                return ResourceManager.GetString("CmdSignalR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direkte Server-Kommunikation.
        /// </summary>
        public static string CmdSignalRToolTip {
            get {
                return ResourceManager.GetString("CmdSignalRToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistik.
        /// </summary>
        public static string CmdStatistics {
            get {
                return ResourceManager.GetString("CmdStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitszeit-Statistiken.
        /// </summary>
        public static string CmdStatisticsToolTip {
            get {
                return ResourceManager.GetString("CmdStatisticsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlls.
        /// </summary>
        public static string CmdTelerik {
            get {
                return ResourceManager.GetString("CmdTelerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlls Demo.
        /// </summary>
        public static string CmdTelerikToolTip {
            get {
                return ResourceManager.GetString("CmdTelerikToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Do.
        /// </summary>
        public static string CmdTodo {
            get {
                return ResourceManager.GetString("CmdTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft-Teams To-Do.
        /// </summary>
        public static string CmdTodoToolTip {
            get {
                return ResourceManager.GetString("CmdTodoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string CmdUser {
            get {
                return ResourceManager.GetString("CmdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Account.
        /// </summary>
        public static string CmdUserToolTip {
            get {
                return ResourceManager.GetString("CmdUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test mit {0} und {1}.
        /// </summary>
        public static string LngTest {
            get {
                return ResourceManager.GetString("LngTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
