//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewHistory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewHistory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewHistory", typeof(ResViewHistory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:00:00.
        /// </summary>
        public static string Lbl_00_00 {
            get {
                return ResourceManager.GetString("Lbl_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24:00:00.
        /// </summary>
        public static string Lbl_23_59 {
            get {
                return ResourceManager.GetString("Lbl_23_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokussierte Arbeit/Projekt.
        /// </summary>
        public static string Lbl_FocusWork {
            get {
                return ResourceManager.GetString("Lbl_FocusWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit in Freizeit.
        /// </summary>
        public static string Lbl_FreeTime {
            get {
                return ResourceManager.GetString("Lbl_FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monat.
        /// </summary>
        public static string Lbl_Month {
            get {
                return ResourceManager.GetString("Lbl_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        public static string Lbl_Total {
            get {
                return ResourceManager.GetString("Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woche.
        /// </summary>
        public static string Lbl_Week {
            get {
                return ResourceManager.GetString("Lbl_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag.
        /// </summary>
        public static string Lbl_WorkingDay {
            get {
                return ResourceManager.GetString("Lbl_WorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit im Planzeitraum.
        /// </summary>
        public static string Lbl_WorkInPlannedTime {
            get {
                return ResourceManager.GetString("Lbl_WorkInPlannedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit in Freizeit.
        /// </summary>
        public static string Lbl_WorkNotInPlannedTime {
            get {
                return ResourceManager.GetString("Lbl_WorkNotInPlannedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
