//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResView", typeof(ResView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Command_Back {
            get {
                return ResourceManager.GetString("Command_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Command_Continue {
            get {
                return ResourceManager.GetString("Command_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Command_Login {
            get {
                return ResourceManager.GetString("Command_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        public static string Command_ResendPassword {
            get {
                return ResourceManager.GetString("Command_ResendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string MsgBox_CancelText {
            get {
                return ResourceManager.GetString("MsgBox_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gespeicherte Daten gehen verloren! Möchtest du wirklich fortfahren? .
        /// </summary>
        public static string MsgBox_DataNotSaved {
            get {
                return ResourceManager.GetString("MsgBox_DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsfehler.
        /// </summary>
        public static string MsgBox_HeaderNoInternet {
            get {
                return ResourceManager.GetString("MsgBox_HeaderNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir wurde ein Link zum Zurücksetzen deines Passwortes zugesand. Überprüfe bitte deinen Posteingang und schaue auch im SPAM-Ordner nach..
        /// </summary>
        public static string MsgBox_NewPasswordSent {
            get {
                return ResourceManager.GetString("MsgBox_NewPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfe deine Internetverbindung.
        /// </summary>
        public static string MsgBox_NoInternet {
            get {
                return ResourceManager.GetString("MsgBox_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string MsgBox_NoText {
            get {
                return ResourceManager.GetString("MsgBox_NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MsgBox_OkText {
            get {
                return ResourceManager.GetString("MsgBox_OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Daten konnten leider nicht gespeichert werden. Versuche es bitte erneut! .
        /// </summary>
        public static string MsgBox_SaveError {
            get {
                return ResourceManager.GetString("MsgBox_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten wurden erfolgreich gespeichert.
        /// </summary>
        public static string MsgBox_SaveSuccess {
            get {
                return ResourceManager.GetString("MsgBox_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung mit dem Server ist leider nicht möglich! .
        /// </summary>
        public static string MsgBox_ServerFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viele aktive Verbindungen, bitte versuche es später erneut!.
        /// </summary>
        public static string MsgBox_ServerMultiConnectionFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerMultiConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout connecting to server!.
        /// </summary>
        public static string MsgBox_ServerTimeout {
            get {
                return ResourceManager.GetString("MsgBox_ServerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerkonto ungültig!.
        /// </summary>
        public static string MsgBox_ServerTokenFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string MsgBox_YesText {
            get {
                return ResourceManager.GetString("MsgBox_YesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff.
        /// </summary>
        public static string MsgBoxAskUserAccessCallCaption {
            get {
                return ResourceManager.GetString("MsgBoxAskUserAccessCallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir würden gerne auf die Anrufliste zugreifen um dir die Anzahl der heutigen Telefonate anzeigen zu können. Das können wir nur tun, wenn du uns den Zugriff erlaubst.
        ///
        ///Wir speichern die Anzahl der Anrufe NICHT und leiten sie auch NICHT an externe Dienste weiter..
        /// </summary>
        public static string MsgBoxAskUserAccessCallCount {
            get {
                return ResourceManager.GetString("MsgBoxAskUserAccessCallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um dir diese Option zu ermöglichen, müssen wir auf deine Anrufliste zugreifen. Dies können wir nur tun, wenn du uns den Zugriff erlaubst.
        ///
        ///Wir speichern NUR die Telefonnummer die du auswählst in deinem ToDo Eintrag, sonst nichts. Wir leiten auch KEINE Daten an externe Dienste weiter..
        /// </summary>
        public static string MsgBoxAskUserAccessCallLog {
            get {
                return ResourceManager.GetString("MsgBoxAskUserAccessCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Kamera. Möchtest du die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxCameraAccess {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Kamera.
        /// </summary>
        public static string MsgBoxCameraAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        public static string MsgBoxCameraAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigungen.
        /// </summary>
        public static string MsgBoxCameraAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf das Dateisystem. Möchtest du die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxFileAccess {
            get {
                return ResourceManager.GetString("MsgBoxFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf das Dateisystem.
        /// </summary>
        public static string MsgBoxFileAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateisystem.
        /// </summary>
        public static string MsgBoxFileAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string MsgBoxFileAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        public static string MsgBoxHeader_DataNotSaved {
            get {
                return ResourceManager.GetString("MsgBoxHeader_DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern fehlgeschlagen.
        /// </summary>
        public static string MsgBoxHeader_SaveError {
            get {
                return ResourceManager.GetString("MsgBoxHeader_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string MsgBoxHeader_SaveSuccess {
            get {
                return ResourceManager.GetString("MsgBoxHeader_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error.
        /// </summary>
        public static string MsgBoxHeader_ServerRestError {
            get {
                return ResourceManager.GetString("MsgBoxHeader_ServerRestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Ortungsdienste. Möchtest du die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxLocationAccess {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Position.
        /// </summary>
        public static string MsgBoxLocationAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string MsgBoxLocationAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string MsgBoxLocationAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt eine neue App- Version {0}. Du nutzt derzeit noch Version {1}. Möchtest du die App jetzt updaten? .
        /// </summary>
        public static string MsgBoxNewUpdate {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Update der App. Bitte kontaktiere den Support.
        /// </summary>
        public static string MsgBoxNewUpdateError {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Es gibt eine neue App-Version {0}. Du nutzt derzeit noch Version {1}. Ein Update ist daher zwingend. Drücke &quot;OK&quot; um das Update der App zu starten. .
        /// </summary>
        public static string MsgBoxNewUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Feature wird auf deinem Gerät leider nicht unterstützt!.
        /// </summary>
        public static string MsgBoxNotSupportedOnPlatform {
            get {
                return ResourceManager.GetString("MsgBoxNotSupportedOnPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht unterstützt!.
        /// </summary>
        public static string MsgBoxNotSupportedOnPlatformCaption {
            get {
                return ResourceManager.GetString("MsgBoxNotSupportedOnPlatformCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update verfügbar.
        /// </summary>
        public static string MsgBoxTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgBoxTitleUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte melde dich erneut an! .
        /// </summary>
        public static string NeedReLogin {
            get {
                return ResourceManager.GetString("NeedReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login benötigt!.
        /// </summary>
        public static string NeedReLoginHead {
            get {
                return ResourceManager.GetString("NeedReLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilbild.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
    }
}
