//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewSettingsWorkTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewSettingsWorkTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewSettingsWorkTime", typeof(ResViewSettingsWorkTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitszeiten speichern .
        /// </summary>
        public static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freitag.
        /// </summary>
        public static string Lbl_Friday {
            get {
                return ResourceManager.GetString("Lbl_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuelle Einstellung pro Tag .
        /// </summary>
        public static string Lbl_Individually {
            get {
                return ResourceManager.GetString("Lbl_Individually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montag.
        /// </summary>
        public static string Lbl_Monday {
            get {
                return ResourceManager.GetString("Lbl_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samstag.
        /// </summary>
        public static string Lbl_Saturday {
            get {
                return ResourceManager.GetString("Lbl_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonntag.
        /// </summary>
        public static string Lbl_Sunday {
            get {
                return ResourceManager.GetString("Lbl_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll-Arbeitszeit.
        /// </summary>
        public static string Lbl_TargetWorkingTimeDaily {
            get {
                return ResourceManager.GetString("Lbl_TargetWorkingTimeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnerstag.
        /// </summary>
        public static string Lbl_Thursday {
            get {
                return ResourceManager.GetString("Lbl_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtarbeitszeit / Woche: .
        /// </summary>
        public static string Lbl_TotalPlannedWorkingTimePerWeek {
            get {
                return ResourceManager.GetString("Lbl_TotalPlannedWorkingTimePerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstag.
        /// </summary>
        public static string Lbl_Tuesday {
            get {
                return ResourceManager.GetString("Lbl_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittwoch.
        /// </summary>
        public static string Lbl_Wednesday {
            get {
                return ResourceManager.GetString("Lbl_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werktags.
        /// </summary>
        public static string Lbl_Workday {
            get {
                return ResourceManager.GetString("Lbl_Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag.
        /// </summary>
        public static string Lbl_WorkingDay {
            get {
                return ResourceManager.GetString("Lbl_WorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planarbeitszeiten.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellung Planarbeitszeiten.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
