//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewFirstLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewFirstLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewFirstLogin", typeof(ResViewFirstLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzbestimmungen.
        /// </summary>
        public static string CmdAgb {
            get {
                return ResourceManager.GetString("CmdAgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los geht’s.
        /// </summary>
        public static string CmdContinue {
            get {
                return ResourceManager.GetString("CmdContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte nimm am Start-Screening teil und hinterlege hier deine Planarbeitszeit..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte nimm am kurzen Start-Screening teil, um danach direkt in der App loslegen zu können .
        /// </summary>
        public static string Lbl_DoFirstSurvey {
            get {
                return ResourceManager.GetString("Lbl_DoFirstSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info-Texte .
        /// </summary>
        public static string Lbl_InfoTexts {
            get {
                return ResourceManager.GetString("Lbl_InfoTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft To-Do.
        /// </summary>
        public static string Lbl_MsToDoSettings {
            get {
                return ResourceManager.GetString("Lbl_MsToDoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Nachrichten .
        /// </summary>
        public static string Lbl_PushSettings {
            get {
                return ResourceManager.GetString("Lbl_PushSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Lbl_Show {
            get {
                return ResourceManager.GetString("Lbl_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start-Screening.
        /// </summary>
        public static string Lbl_StartSurvey {
            get {
                return ResourceManager.GetString("Lbl_StartSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planarbeitszeiten .
        /// </summary>
        public static string Lbl_WorkTimeSettings {
            get {
                return ResourceManager.GetString("Lbl_WorkTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzbestimmungen akzeptiert.
        /// </summary>
        public static string LblAgbAccepted {
            get {
                return ResourceManager.GetString("LblAgbAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So funktioniert die App ....
        /// </summary>
        public static string Text_InfoTexts {
            get {
                return ResourceManager.GetString("Text_InfoTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trage hier den Titel deiner ToDo-Liste ein..
        /// </summary>
        public static string Text_MsToDoSettings {
            get {
                return ResourceManager.GetString("Text_MsToDoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen für Erinnerungen.
        /// </summary>
        public static string Text_PushSettings {
            get {
                return ResourceManager.GetString("Text_PushSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit deiner Teilnahme unterstützt du die Forschung der FH Wiener Neustadt. Dauert nur 5 Minuten..
        /// </summary>
        public static string Text_StartSurvey {
            get {
                return ResourceManager.GetString("Text_StartSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trage hier deine üblichen Arbeitszeiten ein..
        /// </summary>
        public static string Text_WorkTimeSettings {
            get {
                return ResourceManager.GetString("Text_WorkTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine App zur Einteilung von Arbeits- und Freizeit! .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
