//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewToDo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewToDo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewToDo", typeof(ResViewToDo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion deaktiviert. Bitte überprüfe deine Einstellungen!.
        /// </summary>
        public static string FunctionDeactivated {
            get {
                return ResourceManager.GetString("FunctionDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviert.
        /// </summary>
        public static string FunctionDeactivatedCaption {
            get {
                return ResourceManager.GetString("FunctionDeactivatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion scheint mit deinem Microsoft-Konto nicht kompabitel zu sein. Tut uns leid! .
        /// </summary>
        public static string FunctionNotAvailable {
            get {
                return ResourceManager.GetString("FunctionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht verfügbar.
        /// </summary>
        public static string FunctionNotAvailableCaption {
            get {
                return ResourceManager.GetString("FunctionNotAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt.
        /// </summary>
        public static string Lbl_Done {
            get {
                return ResourceManager.GetString("Lbl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Aufgabe.
        /// </summary>
        public static string Lbl_NewTodo {
            get {
                return ResourceManager.GetString("Lbl_NewTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Datum.
        /// </summary>
        public static string Lbl_NoDate {
            get {
                return ResourceManager.GetString("Lbl_NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben.
        /// </summary>
        public static string Lbl_Todo {
            get {
                return ResourceManager.GetString("Lbl_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Do Liste.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
