//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditDay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditDay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditDay", typeof(ResViewEditDay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche Arbeitstag.
        /// </summary>
        public static string BusyContent_OnDelete {
            get {
                return ResourceManager.GetString("BusyContent_OnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag wird gespeichert.
        /// </summary>
        public static string BusyContent_OnSave {
            get {
                return ResourceManager.GetString("BusyContent_OnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag in freien Tag ändern.
        /// </summary>
        public static string Cmd_ConvertToFreeDay {
            get {
                return ResourceManager.GetString("Cmd_ConvertToFreeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freien Tag in Arbeitstag ändern .
        /// </summary>
        public static string Cmd_ConvertToWorkingDay {
            get {
                return ResourceManager.GetString("Cmd_ConvertToWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Cmd_Delete {
            get {
                return ResourceManager.GetString("Cmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block löschen.
        /// </summary>
        public static string Cmd_DeleteBlock {
            get {
                return ResourceManager.GetString("Cmd_DeleteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitblock einfügen.
        /// </summary>
        public static string Cmd_InsertTimeBlock {
            get {
                return ResourceManager.GetString("Cmd_InsertTimeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:00:00.
        /// </summary>
        public static string Lbl_00_00 {
            get {
                return ResourceManager.GetString("Lbl_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24:00:00.
        /// </summary>
        public static string Lbl_23_59 {
            get {
                return ResourceManager.GetString("Lbl_23_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokussierte Arbeit/Projekt.
        /// </summary>
        public static string Lbl_FocusWork {
            get {
                return ResourceManager.GetString("Lbl_FocusWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplante Pause .
        /// </summary>
        public static string Lbl_PlannedPause {
            get {
                return ResourceManager.GetString("Lbl_PlannedPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplantes Arbeitsende.
        /// </summary>
        public static string Lbl_PlannedWorkingTimeEnd {
            get {
                return ResourceManager.GetString("Lbl_PlannedWorkingTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplanter Arbeitsbeginn .
        /// </summary>
        public static string Lbl_PlannedWorkingTimeStart {
            get {
                return ResourceManager.GetString("Lbl_PlannedWorkingTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplante Arbeitsleistung (ohne Pause).
        /// </summary>
        public static string Lbl_PlannedWorkTimeWithoutPause {
            get {
                return ResourceManager.GetString("Lbl_PlannedWorkTimeWithoutPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        public static string Lbl_Total {
            get {
                return ResourceManager.GetString("Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag.
        /// </summary>
        public static string Lbl_WorkingDay {
            get {
                return ResourceManager.GetString("Lbl_WorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit im Planzeitraum.
        /// </summary>
        public static string Lbl_WorkInPlannedTime {
            get {
                return ResourceManager.GetString("Lbl_WorkInPlannedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit in Freizeit.
        /// </summary>
        public static string Lbl_WorkNotInPlannedTime {
            get {
                return ResourceManager.GetString("Lbl_WorkNotInPlannedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Planarbeitstag?.
        /// </summary>
        public static string MsgBox_NoTemplateFound_Caption {
            get {
                return ResourceManager.GetString("MsgBox_NoTemplateFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Planarbeitszeiten für diesen Wochentag gefunden werden. Es wurden daher Standardzeiten voreingestellt..
        /// </summary>
        public static string MsgBox_NoTemplateFound_Text {
            get {
                return ResourceManager.GetString("MsgBox_NoTemplateFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Löschen. Probier&apos;s bitte noch einmal.
        /// </summary>
        public static string MsgBoxCaption_DeleteError {
            get {
                return ResourceManager.GetString("MsgBoxCaption_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen?.
        /// </summary>
        public static string MsgBoxCaption_ReallyDelete {
            get {
                return ResourceManager.GetString("MsgBoxCaption_ReallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern. Probier&apos;s bitte noch einmal.
        /// </summary>
        public static string MsgBoxCaption_SaveError {
            get {
                return ResourceManager.GetString("MsgBoxCaption_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag konnte nicht gelöscht werden!.
        /// </summary>
        public static string MsgBoxText_DeleteError {
            get {
                return ResourceManager.GetString("MsgBoxText_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie diesen Arbeitstag wirklich löschen?.
        /// </summary>
        public static string MsgBoxText_ReallyDelete {
            get {
                return ResourceManager.GetString("MsgBoxText_ReallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen konnten nicht gespeichert werden.
        /// </summary>
        public static string MsgBoxText_SaveError {
            get {
                return ResourceManager.GetString("MsgBoxText_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere Tage.
        /// </summary>
        public static string OtherDays {
            get {
                return ResourceManager.GetString("OtherDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ auswählen                .
        /// </summary>
        public static string PickerTitle_WorkType {
            get {
                return ResourceManager.GetString("PickerTitle_WorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag bearbeiten.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
