//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewMain", typeof(ResViewMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte nimm jetzt am zweiten anonymen Screening teil!.
        /// </summary>
        public static string AddtionalTextSecondSurveyLink {
            get {
                return ResourceManager.GetString("AddtionalTextSecondSurveyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig!.
        /// </summary>
        public static string BusyContentFinished {
            get {
                return ResourceManager.GetString("BusyContentFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade {0}%.
        /// </summary>
        public static string BusyContentLoading {
            get {
                return ResourceManager.GetString("BusyContentLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender .
        /// </summary>
        public static string Cmd_Appointments {
            get {
                return ResourceManager.GetString("Cmd_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anrufe.
        /// </summary>
        public static string Cmd_Calls {
            get {
                return ResourceManager.GetString("Cmd_Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht Stören - Einstellung.
        /// </summary>
        public static string Cmd_DontDisturbSettings {
            get {
                return ResourceManager.GetString("Cmd_DontDisturbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben.
        /// </summary>
        public static string Cmd_ToDos {
            get {
                return ResourceManager.GetString("Cmd_ToDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CmdButtonOk {
            get {
                return ResourceManager.GetString("CmdButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CmdEditDay {
            get {
                return ResourceManager.GetString("CmdEditDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string CmdQuit {
            get {
                return ResourceManager.GetString("CmdQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail senden.
        /// </summary>
        public static string CmdSendEmail {
            get {
                return ResourceManager.GetString("CmdSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail an biss@fotec.at senden.
        /// </summary>
        public static string CmdSendEmailTooltip {
            get {
                return ResourceManager.GetString("CmdSendEmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CmdStartTimer {
            get {
                return ResourceManager.GetString("CmdStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit Start .
        /// </summary>
        public static string CmdStartWorking {
            get {
                return ResourceManager.GetString("CmdStartWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit Stop.
        /// </summary>
        public static string CmdStopWorkingTime {
            get {
                return ResourceManager.GetString("CmdStopWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubMenu.
        /// </summary>
        public static string CmdSubMenu {
            get {
                return ResourceManager.GetString("CmdSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorieren.
        /// </summary>
        public static string CmdSurveyIgnore {
            get {
                return ResourceManager.GetString("CmdSurveyIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusyTest.
        /// </summary>
        public static string CmdTestIsBusy {
            get {
                return ResourceManager.GetString("CmdTestIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit kann zur Zeit nicht gestartet werden!.
        /// </summary>
        public static string ErrorMessage_CantStartWork {
            get {
                return ResourceManager.GetString("ErrorMessage_CantStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Arbeit.
        /// </summary>
        public static string Lbl_AtWork {
            get {
                return ResourceManager.GetString("Lbl_AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Freizeit.
        /// </summary>
        public static string Lbl_DuringFreeTime {
            get {
                return ResourceManager.GetString("Lbl_DuringFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokussierte Arbeit/Projekt.
        /// </summary>
        public static string Lbl_FocusWork {
            get {
                return ResourceManager.GetString("Lbl_FocusWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Arbeitstag!.
        /// </summary>
        public static string Lbl_FreeDay {
            get {
                return ResourceManager.GetString("Lbl_FreeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag liegt in der Zukunft.
        /// </summary>
        public static string Lbl_FutureDay {
            get {
                return ResourceManager.GetString("Lbl_FutureDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann nicht bearbeitet werden.
        /// </summary>
        public static string Lbl_FutureDaySub {
            get {
                return ResourceManager.GetString("Lbl_FutureDaySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunden.
        /// </summary>
        public static string Lbl_Hours {
            get {
                return ResourceManager.GetString("Lbl_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos.
        /// </summary>
        public static string Lbl_Infos {
            get {
                return ResourceManager.GetString("Lbl_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Daten für diesen Tag.
        /// </summary>
        public static string Lbl_NoDataDay {
            get {
                return ResourceManager.GetString("Lbl_NoDataDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag kann nachträglich bearbeitet werden.
        /// </summary>
        public static string Lbl_NoDataDaySub {
            get {
                return ResourceManager.GetString("Lbl_NoDataDaySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute hast du frei! .
        /// </summary>
        public static string Lbl_NoPlanWorkDay {
            get {
                return ResourceManager.GetString("Lbl_NoPlanWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freizeit.
        /// </summary>
        public static string Lbl_NotAtWork {
            get {
                return ResourceManager.GetString("Lbl_NotAtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Lbl_Plan {
            get {
                return ResourceManager.GetString("Lbl_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag ohne reguläre Arbeitszeit.
        /// </summary>
        public static string Lbl_PleaseRecoverToday {
            get {
                return ResourceManager.GetString("Lbl_PleaseRecoverToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag.
        /// </summary>
        public static string Lbl_RegularWorkingDay {
            get {
                return ResourceManager.GetString("Lbl_RegularWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum.
        /// </summary>
        public static string Lbl_TimePeriod {
            get {
                return ResourceManager.GetString("Lbl_TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Lbl_Timer {
            get {
                return ResourceManager.GetString("Lbl_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timertext.
        /// </summary>
        public static string Lbl_TimerText {
            get {
                return ResourceManager.GetString("Lbl_TimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt: .
        /// </summary>
        public static string Lbl_Total {
            get {
                return ResourceManager.GetString("Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit im Planzeitraum.
        /// </summary>
        public static string Lbl_WorkInPlanTime {
            get {
                return ResourceManager.GetString("Lbl_WorkInPlanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit in Freizeit.
        /// </summary>
        public static string Lbl_WorkOutOfPlanTime {
            get {
                return ResourceManager.GetString("Lbl_WorkOutOfPlanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viel Spaß beim Testen der App!.
        /// </summary>
        public static string LblBasic {
            get {
                return ResourceManager.GetString("LblBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMO App der FOTEC Forschungs- und Technologietransfer GMBH des Bereichs Innovative Software Systems (BISS).
        /// </summary>
        public static string LblDemoApp {
            get {
                return ResourceManager.GetString("LblDemoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die FOTEC ist das Forschungsunternehmen der Fachhochschule Wiener Neustadt.
        /// </summary>
        public static string LblFotec {
            get {
                return ResourceManager.GetString("LblFotec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos per E-Mail unter biss@fotec.at.
        /// </summary>
        public static string LblInfo {
            get {
                return ResourceManager.GetString("LblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten nicht möglich wenn Timer läuft..
        /// </summary>
        public static string MsgBox_TimerIsActive {
            get {
                return ResourceManager.GetString("MsgBox_TimerIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten nicht möglich wenn Arbeit läuft..
        /// </summary>
        public static string MsgBox_TimerIsRunning {
            get {
                return ResourceManager.GetString("MsgBox_TimerIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo!.
        /// </summary>
        public static string MsgBoxHello {
            get {
                return ResourceManager.GetString("MsgBoxHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer abbrechen?.
        /// </summary>
        public static string MsgBoxTimerAbortCaption {
            get {
                return ResourceManager.GetString("MsgBoxTimerAbortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du deinen Timer wirklich abbrechen?.
        /// </summary>
        public static string MsgBoxTimerAbortText {
            get {
                return ResourceManager.GetString("MsgBoxTimerAbortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer abbrechen?.
        /// </summary>
        public static string MsgBoxTimerWarningCaption {
            get {
                return ResourceManager.GetString("MsgBoxTimerWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du die Arbeit pausierst, wird dein aktueller Timer gestoppt. Fortfahren?.
        /// </summary>
        public static string MsgBoxTimerWarningEnd {
            get {
                return ResourceManager.GetString("MsgBoxTimerWarningEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du die Arbeit wieder startest, wird dein aktueller Timer gestoppt. Fortfahren?.
        /// </summary>
        public static string MsgBoxTimerWarningStart {
            get {
                return ResourceManager.GetString("MsgBoxTimerWarningStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du tatsächlich ausserhalb deiner geplanten Arbeitszeit arbeiten?.
        /// </summary>
        public static string MsgBoxWorkOutTimeWarning {
            get {
                return ResourceManager.GetString("MsgBoxWorkOutTimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausserhalb der Arbeitszeit.
        /// </summary>
        public static string MsgBoxWorkOutTimeWarningCaption {
            get {
                return ResourceManager.GetString("MsgBoxWorkOutTimeWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokussierte Arbeit/Projekt.
        /// </summary>
        public static string PickerItemFocusWork {
            get {
                return ResourceManager.GetString("PickerItemFocusWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freizeit/Pause.
        /// </summary>
        public static string PickerItemPause {
            get {
                return ResourceManager.GetString("PickerItemPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeit.
        /// </summary>
        public static string PickerItemWork {
            get {
                return ResourceManager.GetString("PickerItemWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOTEC Demo App.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis .
        /// </summary>
        public static string Word_To {
            get {
                return ResourceManager.GetString("Word_To", resourceCulture);
            }
        }
    }
}
